// <auto-generated />
using AProjekt_Supermarked.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AProjektSupermarked.Migrations
{
    [DbContext(typeof(ShoppingContext))]
    [Migration("20180311165342_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AProjekt_Supermarked.Models.IndkobModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Dato");

                    b.Property<int>("Fakturanummer");

                    b.Property<int>("VareID");

                    b.HasKey("Id");

                    b.HasIndex("VareID");

                    b.ToTable("dbsIndkob");
                });

            modelBuilder.Entity("AProjekt_Supermarked.Models.VareModel", b =>
                {
                    b.Property<int>("VareID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Beskrivelse");

                    b.Property<string>("Navn");

                    b.Property<int>("Pris");

                    b.HasKey("VareID");

                    b.ToTable("dbsVare");
                });

            modelBuilder.Entity("AProjekt_Supermarked.Models.IndkobModel", b =>
                {
                    b.HasOne("AProjekt_Supermarked.Models.VareModel", "Vare")
                        .WithMany("Indkob")
                        .HasForeignKey("VareID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
